### ISSUE TITLE
the output version of this project? WLDO? SMALR? or BARC?

### ISSUE THREAD

**Issue by bobby20180331** [OllieBoyne/smal-fitter#4]
@OllieBoyne ,
HI, this is a nice project for I can fit .obj file to smal.pkl very well.
Howerver ,I am a bit confused about the version. 
which one of the following is the direct output of this project ? 
WLDO?  BarC? SMALR?  
Thanks.!
[smal_data_00781_4_all.pkl]:
https://github.com/runa91/barc_release/blob/main/data/smal_data/my_smpl_data_SMBLD_v3.pkl

https://github.com/silviazuffi/smalr_online/blob/master/smpl_models/smal_data_00781_4_all.pkl

https://github.com/benjiebob/WLDO/blob/master/data/smal/my_smpl_data_00781_4_all.pkl

**Comment by OllieBoyne** [comment]
Hi,

This project was made as part of WLDO.

**Comment by bobby20180331** [comment]
@OllieBoyne ,Thanks.
The points that a bit confused is that the smal_data_00781_4_all.pkl in WLDO only have 41 objects other than what they said in the paper (13 dogs was added, it should be 41+13, 54 object?). Why?  

I did know that 18 dogs(5 dogs in smal +13 dogs in big dog package)  was  used in Barc. 

By the way. the smal_data_00781_4_all.pkl was same as WLDO in SMALR, Is that right?

**Comment by OllieBoyne** [comment]
Hi,

It's been a while since I worked on the project, but as I recall:

- The `smal_data_00781_4_all.pkl `is simply the priors as in the SMAL model
- For the extra priors used in the SMBLD dataset, [see here](https://github.com/benjiebob/SMALify/tree/master/data/priors)
- I presume all instances of `smal_data_00781_4_all.pkl` contain the same data.

Hope this helps!
